### ISSUE TITLE
Affinity is Racey

### ISSUE THREAD

**Issue by Smithx10** [joyent/sdc-designation#2]
While trying to make Virtual Kubelet work with triton (https://github.com/Smithx10/virtual-kubelet/tree/triton/providers/triton
) ,   I ran into Racey Affinity rules.  

Here is a snippet from the yaml and affinity rule:

```
/g/i/consul ❯❯❯ cat triton-k8s/deployment.yml                                                                                                                                                                                                   ✘ 130 k8s ✱ ◼
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consul
    matchExpressions:
      - {key: app, operator: In, values: [consul]}
  template:
    metadata:
      annotations:
        package: "9cd95f47-11ea-4f61-c323-fe526fc1c544"
        networks: "a0ae9499-b476-4fef-9861-d0c25029378d, 17d7aa50-6ad9-4e56-93b7-12dc868fac2a"
        affinity: app!=consul
        fwgroup: consul
        fwenabled: "true"
      labels:
        app: consul
        triton.cns.services: consul
    spec:
      restartPolicy: Always
      containers:
      - image: c239a01f-5fe9-456f-8f92-53f5b7efd53d
        name: consul
        ports:
          - containerPort: 8500
            protocol: TCP
            name: consul
          - containerPort: 22
            name: ssh
        envFrom:
        - configMapRef:
            name: consul-config

```

All 3 Instances provisioned on the same node.  

After running 
```
/g/i/consul ❯❯❯ kubectl scale --replicas=5  deployment consul   
```
The 2 instances failed to provision honoring the affinity rule.
```
/g/i/consul ❯❯❯ kubectl get pods                                                                                                                                                                                                                                                                                                                                                                                          ✘ 130 k8s ✱ ◼
NAME                      READY   STATUS           RESTARTS   AGE
consul-57677c6c69-6wdl8   1/1     Running          0          21m
consul-57677c6c69-7gddv   1/1     Running          0          21m
consul-57677c6c69-87gbd   0/1     ProviderFailed   0          18m
consul-57677c6c69-q8tk7   1/1     Running          0          21m
consul-57677c6c69-w5jp4   0/1     ProviderFailed   0          18m
```

Without affinity at run time,  this will make scheduling to Triton via Kubernetes very challenging for a user, and will not honor the normal Kubernetes workflow.  In general this will give Triton users a better experience.


With the help of @jclulow  I was able to track down the history of this issue.

The fix has already been thought out and mentioned in the following bugview. 
https://smartos.org/bugview/PUBAPI-1428
```
1. mixing hard and soft localities would not yet work (currently sdc-docker
handles that case by dropping the soft localities); and
2. DOCKER-1039 is a known issue: Hard affinity rules using instance names or
tags for concurrent provisions will race. The correct fix for that (to
handle the translation from instance name/tags to UUIDs in DAPI's
server selection -- which is serialized in the DC) will fix the issue for
both sdc-docker and CloudAPI.
```
https://smartos.org/bugview/DOCKER-1039
https://github.com/joyent/sdc-cloudapi/blob/97b3c9a69e413a6f339a1f9f2684ce56be0cf0dd/lib/triton-affinity.js#L58-L84

I am willing to try and attempt to resolve this with the proper guidance.  Just point me in the right direction.
